CRM/Controllers/CategReclamsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CRM.Domain.Entities;
using CRM.Models;

namespace CRM.Controllers
{
    public class CategReclamsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: CategReclams
        public ActionResult Index()
        {
            return View(db.CategReclams.ToList());
        }

        // GET: CategReclams/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CategReclam categReclam = db.CategReclams.Find(id);
            if (categReclam == null)
            {
                return HttpNotFound();
            }
            return View(categReclam);
        }

        // GET: CategReclams/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CategReclams/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CategReclamId,ReclamCateg")] CategReclam categReclam)
        {
            if (ModelState.IsValid)
            {
                db.CategReclams.Add(categReclam);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(categReclam);
        }

        // GET: CategReclams/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CategReclam categReclam = db.CategReclams.Find(id);
            if (categReclam == null)
            {
                return HttpNotFound();
            }
            return View(categReclam);
        }

        // POST: CategReclams/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CategReclamId,ReclamCateg")] CategReclam categReclam)
        {
            if (ModelState.IsValid)
            {
                db.Entry(categReclam).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(categReclam);
        }

        // GET: CategReclams/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CategReclam categReclam = db.CategReclams.Find(id);
            if (categReclam == null)
            {
                return HttpNotFound();
            }
            return View(categReclam);
        }

        // POST: CategReclams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CategReclam categReclam = db.CategReclams.Find(id);
            db.CategReclams.Remove(categReclam);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CRM/Controllers/ReclamationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CRM.Domain.Entities;
using CRM.Models;
using CRM.Service;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace CRM.Controllers
{
    public class ReclamationsController : Controller
    {
        ReclamationService RS = new ReclamationService();
     
        private ApplicationDbContext db = new ApplicationDbContext();

        //DataContract for Serializing Data - required to serve in JSON format
        [DataContract]
        public class DataPoint
        {
            public DataPoint(string label, double y)
            {
                this.Label = label;
                this.Y = y;
            }

            [DataMember(Name = "label")]
            public string Label = "";

            [DataMember(Name = "y")]
            public Nullable<double> Y = null;
        }

        // GET: Reclamations
        public ActionResult Index()
        {

            List<DataPoint> data = new List<DataPoint>();

            //List<Reclamation> dataPoints = new List<Reclamation>();
            var reclamation = db.Reclamation.Include(r => r.CategReclam).Include(r => r.Customers).Include(r => r.TypeReclam);
              var dataPoints = reclamation.GroupBy(x => x.TypeReclam, x => x.Status , (groupKey, item) => new
                {
                    key = groupKey,
                    count=item.Count()
                }).ToList();

            //var DataPoints = dataPoints.ToList();
            //ViewBag.DataPoints = JsonConvert.SerializeObject(dataPoints);
            foreach (var item in dataPoints)
            {
                data.Add(new DataPoint(item.key.ReclamType, item.count));
            }

            ViewBag.Statistique = JsonConvert.SerializeObject(data);

                        //Afficher nomre total de réclamation
            ViewBag.nb = RS.CountReclamation();

            return View(reclamation.ToList());
        }

        public ActionResult OrderByStatut()
        {
            var reclamationStatut = from r in db.Reclamation
                                    orderby r.Status ascending
                                    select r;
                return View(reclamationStatut);
        }

        //public ActionResult groupReclam()
        //{
        //    //List<Reclamation> group = new List<Reclamation>;
        //    var groupList = db.Reclamation
        //        .GroupBy(x => x.TypeReclam, x => x, (groupKey, item) => new
        //    {
        //        key = groupKey,
        //        item = item.ToList()
        //    }).ToList();

        //    return View(groupList.ToList());
        //}

        [HttpPost]
        public ActionResult Index(string searchString)
        {
            List<Reclamation> lists = new List<Reclamation>();
            var reclamation = db.Reclamation.Include(r => r.CategReclam).Include(r => r.Customers).Include(r => r.TypeReclam);

            if (!String.IsNullOrEmpty(searchString))
            {
                lists = reclamation.ToList().Where(m => m.ReclamSubject.Contains(searchString)).ToList();
        }

            return View(lists);
        }


        // GET: Reclamations/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reclamation reclamation = db.Reclamation.Find(id);
            if (reclamation == null)
            {
                return HttpNotFound();
            }
            return View(reclamation);
        }

        // GET: Reclamations/Create
        public ActionResult Create()
        {
            ViewBag.CategReclamId = new SelectList(db.CategReclams, "CategReclamId", "ReclamCateg");
            ViewBag.CustomerId = new SelectList(db.Customers, "CustomerId", "Email");
            ViewBag.TypeReclamId = new SelectList(db.TypeReclams, "TypeReclamId", "ReclamType");
            return View();
        }

        // POST: Reclamations/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ReclamId,Status,ReclamSubject,Description,ReclamStartDate,CustomerId,TypeReclamId,CategReclamId")] Reclamation reclamation)
        {
            if (ModelState.IsValid)
            {
                db.Reclamation.Add(reclamation);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategReclamId = new SelectList(db.CategReclams, "CategReclamId", "ReclamCateg", reclamation.CategReclamId);
            ViewBag.CustomerId = new SelectList(db.Customers, "CustomerId", "Email", reclamation.CustomerId);
            ViewBag.TypeReclamId = new SelectList(db.TypeReclams, "TypeReclamId", "ReclamType", reclamation.TypeReclamId);
            return View(reclamation);
        }

        // GET: Reclamations/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reclamation reclamation = db.Reclamation.Find(id);
            if (reclamation == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategReclamId = new SelectList(db.CategReclams, "CategReclamId", "ReclamCateg", reclamation.CategReclamId);
            ViewBag.CustomerId = new SelectList(db.Customers, "CustomerId", "Email", reclamation.CustomerId);
            ViewBag.TypeReclamId = new SelectList(db.TypeReclams, "TypeReclamId", "ReclamType", reclamation.TypeReclamId);
            return View(reclamation);
        }

        // POST: Reclamations/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ReclamId,Status,ReclamSubject,Description,ReclamStartDate,CustomerId,TypeReclamId,CategReclamId")] Reclamation reclamation)
        {
            if (ModelState.IsValid)
            {
                db.Entry(reclamation).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategReclamId = new SelectList(db.CategReclams, "CategReclamId", "ReclamCateg", reclamation.CategReclamId);
            ViewBag.CustomerId = new SelectList(db.Customers, "CustomerId", "Email", reclamation.CustomerId);
            ViewBag.TypeReclamId = new SelectList(db.TypeReclams, "TypeReclamId", "ReclamType", reclamation.TypeReclamId);
            return View(reclamation);
        }

        // GET: Reclamations/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reclamation reclamation = db.Reclamation.Find(id);
            if (reclamation == null)
            {
                return HttpNotFound();
            }
            return View(reclamation);
        }

        // POST: Reclamations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Reclamation reclamation = db.Reclamation.Find(id);
            db.Reclamation.Remove(reclamation);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CRM/Controllers/TypeReclamsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CRM.Domain.Entities;
using CRM.Models;

namespace CRM.Controllers
{
    public class TypeReclamsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: TypeReclams
        public ActionResult Index()
        {
            return View(db.TypeReclams.ToList());
        }

        // GET: TypeReclams/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TypeReclam typeReclam = db.TypeReclams.Find(id);
            if (typeReclam == null)
            {
                return HttpNotFound();
            }
            return View(typeReclam);
        }

        // GET: TypeReclams/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TypeReclams/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TypeReclamId,ReclamType")] TypeReclam typeReclam)
        {
            if (ModelState.IsValid)
            {
                db.TypeReclams.Add(typeReclam);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(typeReclam);
        }

        // GET: TypeReclams/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TypeReclam typeReclam = db.TypeReclams.Find(id);
            if (typeReclam == null)
            {
                return HttpNotFound();
            }
            return View(typeReclam);
        }

        // POST: TypeReclams/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TypeReclamId,ReclamType")] TypeReclam typeReclam)
        {
            if (ModelState.IsValid)
            {
                db.Entry(typeReclam).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(typeReclam);
        }

        // GET: TypeReclams/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TypeReclam typeReclam = db.TypeReclams.Find(id);
            if (typeReclam == null)
            {
                return HttpNotFound();
            }
            return View(typeReclam);
        }

        // POST: TypeReclams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TypeReclam typeReclam = db.TypeReclams.Find(id);
            db.TypeReclams.Remove(typeReclam);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CRM/Views/Reclamations/Create.cshtml
@model CRM.Domain.Entities.Reclamation

@{
    ViewBag.Title = "Create";
}

<h2>Nouvelle Réclamation</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Reclamation</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Status, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReclamSubject, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReclamSubject, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReclamSubject, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReclamStartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReclamStartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReclamStartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerId, "CustomerId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CustomerId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CustomerId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TypeReclamId, "TypeReclamId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TypeReclamId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TypeReclamId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategReclamId, "CategReclamId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategReclamId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategReclamId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retour à la Liste", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CRM/Views/Reclamations/Delete.cshtml
@model CRM.Domain.Entities.Reclamation

@{
    ViewBag.Title = "Delete";
}

<h2>Supprimer Réclamation</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Reclamation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CategReclam.ReclamCateg)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategReclam.ReclamCateg)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Customers.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customers.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TypeReclam.ReclamType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TypeReclam.ReclamType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReclamSubject)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReclamSubject)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReclamStartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReclamStartDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Retour à la Liste", "Index")
        </div>
    }
</div>

CRM/Views/Reclamations/Details.cshtml
@model CRM.Domain.Entities.Reclamation

@{
    ViewBag.Title = "Details";
}

<h2>Détails de la Réclamation</h2>

<div>
    <h4>Réclamation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CategReclam.ReclamCateg)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategReclam.ReclamCateg)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Customers.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customers.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TypeReclam.ReclamType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TypeReclam.ReclamType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReclamSubject)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReclamSubject)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReclamStartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReclamStartDate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ReclamId }) |
    @Html.ActionLink("Retour à la Liste", "Index")
</p>

CRM/Views/Reclamations/Index.cshtml
@model IEnumerable<CRM.Domain.Entities.Reclamation>

@{
    ViewBag.Title = "Index";
}

<nav class="navbar-left">
   @* <ul class="nav navbar-nav">*@
        <ul>@Html.ActionLink("Créer Nouvelle Réclamation", "Create")</ul>
        <ul>@Html.ActionLink("Ordre par Statut", "OrderByStatut")</ul>
        <ul>@Html.ActionLink("Afficher tout", "Index")</ul>
        <ul>@Html.ActionLink("Ajout Type Réclamation", "Create", "TypeReclams")</ul>
        <ul>@Html.ActionLink("Ajout Catégorie Réclamation", "Create", "CategReclams")</ul>
    @*</ul>*@
</nav>

    <h2 style="text-align:left">Gestion Réclamation</h2>
    <h3 style="text-align:left">Nombre Totale réclamations est : <B>@ViewBag.nb</B></h3>
    
    @*Pie Graphique*@
    <script type="text/javascript">
        window.onload = function () {
            var chart = new CanvasJS.Chart("chartContainer", {
                theme: "light1", // "light1", "light2", "dark1", "dark2"
                exportEnabled: true,
                animationEnabled: true,
                title: {
                    text: "Répartition par type de réclamation"
                },
                //subtitles: [{
                //    text: "Q2, 2016"
                //}],
                data: [{
                    type: "pie",
                    startAngle: 180,
                    toolTipContent: "<b>{label}</b>: {y}",
                    showInLegend: "true",
                    legendText: "{label}",
                    indexLabel: "{label} - {y}",
                    dataPoints: @Html.Raw(ViewBag.Statistique),
                }]
            });
            chart.render();
        };
    </script>


<body>
    <div id="chartContainer" style="height: 250px; width: 100%;">    </div>
    <script src="~/Scripts/canvasjs.min.js"></script>
        @using (Html.BeginForm())
        {
            @*Bouton de recherches*@
            <table>
                <tr>
                    <td>
                        <div>
                            Recherche par Objet : @Html.TextBox("searchString")
                        </div>
                    </td>
                    <td> <input type="submit" value="Rechercher" id="recherche" /> </td>
                </tr>
            </table>
        }

        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.CategReclam.ReclamCateg)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TypeReclam.ReclamType)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Status)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Customers.Email)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ReclamSubject)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ReclamStartDate)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.CategReclam.ReclamCateg)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TypeReclam.ReclamType)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Status)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Customers.Email)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ReclamSubject)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ReclamStartDate)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.ReclamId }) |
                        @Html.ActionLink("Details", "Details", new { id = item.ReclamId }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.ReclamId })
                    </td>
                </tr>
            }

        </table>
</body>

CRM/Views/Reclamations/OrderByStatut.cshtml
@model IEnumerable<CRM.Domain.Entities.Reclamation>

@{
    ViewBag.Title = "OrderByStatut";
}

<h2>Ordre par Statut</h2>

<p>
    @Html.ActionLink("Retour à la liste", "Index")
</p>
<table class="table">
    <tr>
        @*<th>
            @Html.DisplayNameFor(model => model.CategReclam.ReclamCateg)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Customers.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TypeReclam.ReclamType)
        </th>*@
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ReclamSubject)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ReclamStartDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        @*<td>
            @Html.DisplayFor(modelItem => item.CategReclam.ReclamCateg)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Customers.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TypeReclam.ReclamType)
        </td>*@
        <td>
            @Html.DisplayFor(modelItem => item.Status)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ReclamSubject)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ReclamStartDate)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ReclamId }) |
            @Html.ActionLink("Details", "Details", new { id=item.ReclamId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ReclamId })
        </td>
    </tr>
}

</table>